<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.youngmonkeys</groupId>
        <artifactId>ezyplatform-parent</artifactId>
        <version>0.0.2</version>
    </parent>
    <artifactId>ezyrag</artifactId>
    <groupId>org.youngmonkeys</groupId>
    <version>0.0.1</version>
    <packaging>pom</packaging>

    <name>ezyrag</name>
    <description>EzyRag</description>

    <properties>
        <!--suppress UnresolvedMavenProperty -->
        <ezyplatform.home>${env.EZYPLATFORM_HOME}</ezyplatform.home>
    </properties>

    <modules>
        <module>ezyrag-sdk</module>
        <module>ezyrag-socket-plugin</module>
        <module>ezyrag-admin-plugin</module>
        <module>ezyrag-web-plugin</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-test-sdk</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${maven.checkstyle.plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>com.puppycrawl.tools</groupId>
                        <artifactId>checkstyle</artifactId>
                        <version>8.42</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <consoleOutput>true</consoleOutput>
                    <violationSeverity>warning</violationSeverity>
                    <configLocation>checkstyle.xml</configLocation>
                </configuration>
                <executions>
                    <execution>
                        <id>verify</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
