type=socket-plugin
version=0.0.1
package=org.youngmonkeys.ezyrag.socket.plugin
project_name=EzyRag
zone.name=ezyrag
entry_loader=org.youngmonkeys.ezyrag.socket.plugin.PluginEntryLoader
listen_events=USER_LOGIN
zone.setting_file=ezyrag-zone-settings.xml
description=Socket plugin for EzyRag
author=tvd12
