<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
 ~ Copyright 2026 youngmonkeys.org
 ~ 
 ~ Licensed under the ezyplatform, Version 1.0.0 (the "License");
 ~ you may not use this file except in compliance with the License.
 ~ You may obtain a copy of the License at
 ~ 
 ~     https://youngmonkeys.org/licenses/ezyplatform-1.0.0.txt
 ~ 
 ~ Unless required by applicable law or agreed to in writing, software
 ~ distributed under the License is distributed on an "AS IS" BASIS,
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ~ See the License for the specific language governing permissions and
 ~ limitations under the License.
--><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.youngmonkeys</groupId>
        <artifactId>ezyrag</artifactId>
        <version>0.0.5</version>
    </parent>

    <artifactId>ezyrag-socket-plugin</artifactId>
    <name>ezyrag-socket-plugin</name>
    <url>https://youngmonkeys.org</url>

    <dependencies>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-socket-sdk</artifactId>
            <version>${ezy.platform.version}</version>
        </dependency>
        <!-- start add sdk dependency -->
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyrag-sdk</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- end add sdk dependency -->
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-common</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/lib/ezyplatform-common-${ezy.platform.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-socket</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/socket/lib/ezyplatform-socket-${ezy.platform.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.tvd12</groupId>
            <artifactId>ezyfox-server-embedded</artifactId>
            <version>${ezy.version}</version>
            <scope>test</scope>
        </dependency>
    <dependency>
			<groupId>com.tvd12</groupId>
			<artifactId>ezyfox-monitor</artifactId>
			<version>${ezy.version}</version>
		<scope>provided</scope>
        </dependency>
        <dependency>
			<groupId>com.tvd12</groupId>
			<artifactId>ezyfox-server-support</artifactId>
			<version>${ezy.version}</version>
		<scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyai-sdk</artifactId>
            <version>${ezyai.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/socket/plugins/ezyai/lib/ezyai-sdk-${ezyai.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyarticle-sdk</artifactId>
            <version>${ezyarticle.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/socket/plugins/ezyarticle/lib/ezyarticle-sdk-${ezyarticle.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezychat-sdk</artifactId>
            <version>${ezychat.version}</version>
        <scope>system</scope>
            <systemPath>${ezyplatform.home}/socket/apps/ezychat/lib/ezychat-sdk-${ezychat.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezychat-socket-app</artifactId>
            <version>${ezychat.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/socket/apps/ezychat/lib/ezychat-socket-app-${ezychat.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezychat-socket-plugin</artifactId>
            <version>${ezychat.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/socket/plugins/ezychat/lib/ezychat-socket-plugin-${ezychat.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>graphql-sdk</artifactId>
            <version>${graphql.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/socket/plugins/graphql/lib/graphql-sdk-${graphql.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>graphql-socket-plugin</artifactId>
            <version>${graphql.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/socket/plugins/graphql/lib/graphql-socket-plugin-${graphql.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>socket-monitor</artifactId>
            <version>${socket.monitor.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/socket/plugins/socket-monitor/lib/socket-monitor-${socket.monitor.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyai-socket-plugin</artifactId>
            <version>${ezyai.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/socket/plugins/ezyai/lib/ezyai-socket-plugin-${ezyai.version}.jar</systemPath>
        </dependency>
    <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ecommerce-sdk</artifactId>
            <version>${ecommerce.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/socket/plugins/ecommerce/lib/ecommerce-sdk-${ecommerce.version}.jar</systemPath>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>test</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                    </resource>
                    <resource>
                        <directory>${ezyplatform.home}/settings</directory>
                    </resource>
                    <resource>
                        <directory>${ezyplatform.home}/socket/settings</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/socket/plugins/ezyai/resources</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/socket/plugins/ezychat/resources</directory>
                    </resource>
                <resource>
                        <directory>${ezyplatform.home}/socket/plugins/graphql/resources</directory>
                    </resource>
                </resources>
            </build>
        </profile>
    </profiles>
</project>
