<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.youngmonkeys</groupId>
        <artifactId>ezyrag</artifactId>
        <version>0.0.1</version>
    </parent>

    <artifactId>ezyrag-socket-plugin</artifactId>
    <name>ezyrag-socket-plugin</name>
    <url>https://youngmonkeys.org</url>

    <dependencies>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-socket-sdk</artifactId>
            <version>${ezy.platform.version}</version>
        </dependency>
        <!-- start add sdk dependency -->
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyrag-sdk</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- end add sdk dependency -->
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-common</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/lib/ezyplatform-common-${ezy.platform.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.youngmonkeys</groupId>
            <artifactId>ezyplatform-socket</artifactId>
            <version>${ezy.platform.version}</version>
            <scope>system</scope>
            <systemPath>${ezyplatform.home}/socket/lib/ezyplatform-socket-${ezy.platform.version}.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.tvd12</groupId>
            <artifactId>ezyfox-server-embedded</artifactId>
            <version>${ezy.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>test</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <build>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                    </resource>
                    <resource>
                        <directory>${ezyplatform.home}/settings</directory>
                    </resource>
                    <resource>
                        <directory>${ezyplatform.home}/socket/settings</directory>
                    </resource>
                </resources>
            </build>
        </profile>
    </profiles>
</project>
